// <auto-generated />
using System;
using ApiDex.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiDex.Infrastructure.Data
{
    [DbContext(typeof(ApiDexDbContext))]
    [Migration("20260522160407_AddRagRuntimeSettings")]
    partial class AddRagRuntimeSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ApiDex")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiDex.Infrastructure.Data.Entity.DocumentationProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArchitectureType")
                        .HasColumnType("integer");

                    b.Property<string>("GeneralDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("DocumentationProjects", "ApiDex");
                });

            modelBuilder.Entity("ApiDex.Infrastructure.Data.Entity.RagSettingsEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ActiveModel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ContextMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("TopKChunks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RagSettings", "ApiDex");
                });

            modelBuilder.Entity("ApiDex.Infrastructure.Data.Entity.ServiceDependencyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DependencyType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ServiceDocumentationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceEndpointId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetEndpointId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetEndpointRoute")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TargetServiceTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceDocumentationId");

                    b.HasIndex("SourceEndpointId");

                    b.HasIndex("TargetEndpointId");

                    b.ToTable("ServiceDependencies", "ApiDex");
                });

            modelBuilder.Entity("ApiDex.Infrastructure.Data.Entity.ServiceDocumentationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentationProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("GeneralDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentationProjectId", "Title")
                        .IsUnique();

                    b.ToTable("ServiceDocumentations", "ApiDex");
                });

            modelBuilder.Entity("ApiDex.Infrastructure.Data.Entity.ServiceEndpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ServiceDocumentationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceDocumentationId", "Key")
                        .IsUnique();

                    b.ToTable("ServiceEndpoints", "ApiDex");
                });

            modelBuilder.Entity("ApiDex.Infrastructure.Data.Entity.ServiceEventEndpointEntity", b =>
                {
                    b.Property<Guid>("ServiceEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceEndpointId")
                        .HasColumnType("uuid");

                    b.HasKey("ServiceEventId", "ServiceEndpointId");

                    b.HasIndex("ServiceEndpointId");

                    b.ToTable("ServiceEventEndpoints", "ApiDex");
                });

            modelBuilder.Entity("ApiDex.Infrastructure.Data.Entity.ServiceEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ServiceDocumentationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceDocumentationId");

                    b.ToTable("ServiceEvents", "ApiDex");
                });

            modelBuilder.Entity("ApiDex.Infrastructure.Data.Entity.ServiceDependencyEntity", b =>
                {
                    b.HasOne("ApiDex.Infrastructure.Data.Entity.ServiceDocumentationEntity", "ServiceDocumentation")
                        .WithMany("Dependencies")
                        .HasForeignKey("ServiceDocumentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiDex.Infrastructure.Data.Entity.ServiceEndpointEntity", "SourceEndpoint")
                        .WithMany("SourceDependencies")
                        .HasForeignKey("SourceEndpointId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApiDex.Infrastructure.Data.Entity.ServiceEndpointEntity", "TargetEndpoint")
                        .WithMany("TargetDependencies")
                        .HasForeignKey("TargetEndpointId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ServiceDocumentation");

                    b.Navigation("SourceEndpoint");

                    b.Navigation("TargetEndpoint");
                });

            modelBuilder.Entity("ApiDex.Infrastructure.Data.Entity.ServiceDocumentationEntity", b =>
                {
                    b.HasOne("ApiDex.Infrastructure.Data.Entity.DocumentationProjectEntity", "DocumentationProject")
                        .WithMany("Services")
                        .HasForeignKey("DocumentationProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentationProject");
                });

            modelBuilder.Entity("ApiDex.Infrastructure.Data.Entity.ServiceEndpointEntity", b =>
                {
                    b.HasOne("ApiDex.Infrastructure.Data.Entity.ServiceDocumentationEntity", "ServiceDocumentation")
                        .WithMany("Endpoints")
                        .HasForeignKey("ServiceDocumentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceDocumentation");
                });

            modelBuilder.Entity("ApiDex.Infrastructure.Data.Entity.ServiceEventEndpointEntity", b =>
                {
                    b.HasOne("ApiDex.Infrastructure.Data.Entity.ServiceEndpointEntity", "ServiceEndpoint")
                        .WithMany("EventEndpoints")
                        .HasForeignKey("ServiceEndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiDex.Infrastructure.Data.Entity.ServiceEventEntity", "ServiceEvent")
                        .WithMany("EventEndpoints")
                        .HasForeignKey("ServiceEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceEndpoint");

                    b.Navigation("ServiceEvent");
                });

            modelBuilder.Entity("ApiDex.Infrastructure.Data.Entity.ServiceEventEntity", b =>
                {
                    b.HasOne("ApiDex.Infrastructure.Data.Entity.ServiceDocumentationEntity", "ServiceDocumentation")
                        .WithMany("Events")
                        .HasForeignKey("ServiceDocumentationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceDocumentation");
                });

            modelBuilder.Entity("ApiDex.Infrastructure.Data.Entity.DocumentationProjectEntity", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("ApiDex.Infrastructure.Data.Entity.ServiceDocumentationEntity", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Endpoints");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("ApiDex.Infrastructure.Data.Entity.ServiceEndpointEntity", b =>
                {
                    b.Navigation("EventEndpoints");

                    b.Navigation("SourceDependencies");

                    b.Navigation("TargetDependencies");
                });

            modelBuilder.Entity("ApiDex.Infrastructure.Data.Entity.ServiceEventEntity", b =>
                {
                    b.Navigation("EventEndpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
